{% set name = "jupyterhub-kubespawner" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: dd32147e692e65f3694e7a9d44503f5282357dc46340ecdc2e63c07e9cc5b074

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - escapism
    - jinja2
    - jupyterhub >=1.3.0
    - kubernetes_asyncio >=23.6.0
    - python-slugify
    - pyyaml
    - traitlets >=4.3.2
    - urllib3

test:
  imports:
    - kubespawner

about:
  home: https://github.com/jupyterhub/kubespawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kubernetes spawner for JupyterHub

extra:
  recipe-maintainers:
    - consideratio
    - dhirschfeld
