{% set name = "jupyterhub-kubespawner" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ac36cddc8229f3818e6ba08628d71ede991da253f49c3c1de3acba2fab98a44f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - escapism
    - jinja2
    - jupyterhub >=4.0.0
    - kubernetes_asyncio >=24.2.3
    - python-slugify
    - pyyaml
    - traitlets
    - urllib3

test:
  imports:
    - kubespawner

about:
  home: https://github.com/jupyterhub/kubespawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kubernetes spawner for JupyterHub

extra:
  recipe-maintainers:
    - consideratio
    - dhirschfeld
