{% set name = "jupyterhub-kubespawner" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0ad2bb4232670870531900906ebe9fc081b3327fd65921cf87661661ad1eda7b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - escapism
    - jinja2
    - jupyterhub >=4.0.0
    - kubernetes_asyncio >=24.2.3
    - python-slugify
    - pyyaml
    - traitlets
    - urllib3

test:
  imports:
    - kubespawner

about:
  home: https://github.com/jupyterhub/kubespawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kubernetes spawner for JupyterHub

extra:
  recipe-maintainers:
    - consideratio
    - dhirschfeld
