{% set name = "jupyterhub-kubespawner" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ce1a5618fea2477962e640fb462e2be6fc69b8f1192ea08da421d8673495458

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - escapism
    - jinja2
    - jupyterhub >=0.9
    - kubernetes_asyncio >=19.15.1
    - python-slugify
    - pyyaml
    - urllib3

test:
  imports:
    - kubespawner

about:
  home: https://github.com/jupyterhub/kubespawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kubernetes spawner for JupyterHub

extra:
  recipe-maintainers:
    - consideratio
    - dhirschfeld
