{% set name = "jupyterhub-kubespawner" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 38815cb83ff5cba78e916efc4164e8899bfacab4423628029cd4867968b89b18

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - escapism
    - jinja2
    - jupyterhub >=4.0.0
    - kubernetes_asyncio >=24.2.3
    - python-slugify
    - pyyaml
    - traitlets
    - urllib3

test:
  requires:
    - python {{ python_min }}
  imports:
    - kubespawner

about:
  home: https://github.com/jupyterhub/kubespawner
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Kubernetes spawner for JupyterHub

extra:
  recipe-maintainers:
    - consideratio
    - dhirschfeld
